services:
  - type: web
    name: kot-bot
    env: node
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    healthCheckPath: /ping
    autoDeploy: true
