services:
  - type: web
    name: kot-slack-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /ping
    autoDeploy: true